import type { ItemDef } from "../core/types";

/**
 * アイテム図鑑。名前はすべてオリジナル(一般的なファンタジー語彙)。
 * model は public/models/<model>.glb に対応し、同じカテゴリは同じモデルを色違いで使う。
 */
export const ITEMS: readonly ItemDef[] = [
  // ---- 草 ----
  {
    id: "healLeaf",
    name: "いやしの葉",
    category: "herb",
    model: "herb",
    effect: "heal",
    power: 25,
    minFloor: 1,
    weight: 12,
    description: "HPを25回復する。",
  },
  {
    id: "greatLeaf",
    name: "大いやしの葉",
    category: "herb",
    model: "herb",
    effect: "heal",
    power: 60,
    minFloor: 4,
    weight: 5,
    description: "HPを60回復する。",
  },
  {
    id: "powerLeaf",
    name: "ちからの葉",
    category: "herb",
    model: "herb",
    effect: "power",
    power: 1,
    minFloor: 3,
    weight: 3,
    description: "attackが永続的に1上がる。",
  },
  {
    id: "wakeGrass",
    name: "めざめ草",
    category: "herb",
    model: "herb",
    effect: "cureSleepConfuse",
    minFloor: 2,
    weight: 5,
    description: "眠り・混乱を即座に治す。",
  },
  {
    id: "antidoteBerry",
    name: "毒消しの実",
    category: "herb",
    model: "herb",
    effect: "curePoison",
    minFloor: 2,
    weight: 5,
    description: "毒を即座に治す。",
  },
  {
    id: "toughLeaf",
    name: "がんじょうの葉",
    category: "herb",
    model: "herb",
    effect: "defenseUp",
    power: 1,
    minFloor: 3,
    weight: 3,
    description: "defenseが永続的に1上がる。",
  },
  {
    id: "waypointLeaf",
    name: "みちしるべの葉",
    category: "herb",
    model: "herb",
    effect: "senseStairs",
    minFloor: 1,
    weight: 6,
    description: "階段の位置と、そこまでの大まかな道筋だけが分かる。",
  },

  // ---- 巻物 ----
  {
    id: "sleepScroll",
    name: "ねむりの巻物",
    category: "scroll",
    model: "scroll",
    effect: "sleepRoom",
    power: 8,
    minFloor: 2,
    weight: 6,
    description: "同じ部屋のモンスターを眠らせる。",
  },
  {
    id: "mapScroll",
    name: "地図の巻物",
    category: "scroll",
    model: "scroll",
    effect: "revealMap",
    minFloor: 1,
    weight: 7,
    description: "このフロアの地形がすべて分かる。",
  },
  {
    id: "confuseScroll",
    name: "混乱の巻物",
    category: "scroll",
    model: "scroll",
    effect: "confuseRoom",
    power: 8,
    minFloor: 3,
    weight: 5,
    description: "同じ部屋のモンスターを混乱させる。",
  },
  {
    id: "invisibilityScroll",
    name: "とうめいの巻物",
    category: "scroll",
    model: "scroll",
    effect: "invisibility",
    power: 5,
    minFloor: 4,
    weight: 4,
    description: "数ターンの間、モンスターに新たに発見されなくなる。",
  },
  {
    id: "fearScroll",
    name: "おびえの巻物",
    category: "scroll",
    model: "scroll",
    effect: "fearRoom",
    power: 6,
    minFloor: 2,
    weight: 5,
    description: "同じ部屋のモンスターをおびえさせ、逃走させる。",
  },

  // ---- 杖 ----
  {
    id: "swapStaff",
    name: "場所替えの杖",
    category: "staff",
    model: "staff",
    effect: "swap",
    charges: 4,
    minFloor: 2,
    weight: 5,
    description: "向いている方向のモンスターと位置を入れ替える。",
  },
  {
    id: "sleepStaff",
    name: "ねむりの杖",
    category: "staff",
    model: "staff",
    effect: "sleepTarget",
    power: 6,
    charges: 4,
    minFloor: 3,
    weight: 5,
    description: "向いている方向のモンスターを眠らせる。",
  },
  {
    id: "pullStaff",
    name: "引き寄せの杖",
    category: "staff",
    model: "staff",
    effect: "pull",
    charges: 4,
    minFloor: 3,
    weight: 4,
    description: "向いている方向のモンスターを1マス引き寄せる。",
  },
  {
    id: "sealStaff",
    name: "かなしばりの杖",
    category: "staff",
    model: "staff",
    effect: "sealTarget",
    power: 6,
    charges: 4,
    minFloor: 4,
    weight: 4,
    description: "向いている方向のモンスターを封じる(特技が使えなくなる)。",
  },

  // ---- 食料 ----
  {
    id: "hardBread",
    name: "かたパン",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 45,
    minFloor: 1,
    weight: 10,
    description: "満腹度を45回復する。",
  },
  {
    id: "bigBread",
    name: "大きなパン",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 100,
    minFloor: 3,
    weight: 4,
    description: "満腹度を100回復する。",
  },
  {
    id: "mountainBounty",
    name: "山の幸",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 150,
    minFloor: 6,
    weight: 3,
    description: "満腹度を150回復する。",
  },
  {
    id: "driedBerries",
    name: "ほしぼし",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 15,
    minFloor: 1,
    weight: 10,
    description: "満腹度を15回復する。軽くて持ち歩きやすい。",
  },

  // ---- 武器 ----
  // 系統ごとに attackPattern が異なる。plan/protagonist-weapons.md 参照。
  // 各系統は入手階層違いの基本形・上位形の2段構成(既存のなた/鉄のなたと揃える)。
  {
    id: "hatchet",
    name: "なた",
    category: "weapon",
    model: "hatchet",
    bonus: 4,
    minFloor: 1,
    weight: 5,
    description: "attack+4。隣接1マスを攻撃する、もっとも素直な性能。",
  },
  {
    id: "ironHatchet",
    name: "鉄のなた",
    category: "weapon",
    model: "hatchet",
    bonus: 9,
    minFloor: 5,
    weight: 3,
    description: "attack+9。隣接1マスを攻撃する、もっとも素直な性能。",
  },
  {
    id: "spearedge",
    name: "穂突き",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "line2",
    minFloor: 2,
    weight: 4,
    description: "attack+3。正面2マス先まで直線に届く(間の敵も巻き込む)。",
  },
  {
    id: "greatSpearedge",
    name: "長穂突き",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "line2",
    minFloor: 6,
    weight: 3,
    description: "attack+7。正面2マス先まで直線に届く(間の敵も巻き込む)。",
  },
  {
    id: "broadaxe",
    name: "大鉈",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "arc3",
    minFloor: 3,
    weight: 4,
    description: "attack+3。向いている方向を中心に正面と斜め前2方向、計3マスを攻撃する。",
  },
  {
    id: "greatBroadaxe",
    name: "大鉈・重",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "arc3",
    minFloor: 7,
    weight: 3,
    description: "attack+7。向いている方向を中心に正面と斜め前2方向、計3マスを攻撃する。",
  },
  {
    id: "barrelHook",
    name: "双樽鉤",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "quickSingle",
    minFloor: 4,
    weight: 4,
    description: "attack+3。会心率+15%、そのラン最初の1手は必ず会心の一撃になる。",
  },
  {
    id: "greatBarrelHook",
    name: "双樽鉤・双牙",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "quickSingle",
    minFloor: 8,
    weight: 3,
    description: "attack+7。会心率+15%、そのラン最初の1手は必ず会心の一撃になる。",
  },
  {
    id: "lordsMaul",
    name: "主の大槌",
    category: "weapon",
    model: "hatchet",
    bonus: 6,
    attackPattern: "heavySingle",
    minFloor: 5,
    weight: 3,
    description: "attack+6。振るった反動で、次の1手ぶん行動が遅れる。",
  },
  {
    id: "greatLordsMaul",
    name: "主の大槌・銘",
    category: "weapon",
    model: "hatchet",
    bonus: 12,
    attackPattern: "heavySingle",
    minFloor: 9,
    weight: 2,
    description: "attack+12。振るった反動で、次の1手ぶん行動が遅れる。",
  },

  // ---- 盾 ----
  {
    id: "woodShield",
    name: "木の盾",
    category: "shield",
    model: "shield",
    bonus: 3,
    minFloor: 1,
    weight: 5,
    description: "defense+3",
  },
  {
    id: "ironShield",
    name: "鉄の盾",
    category: "shield",
    model: "shield",
    bonus: 7,
    minFloor: 5,
    weight: 3,
    description: "defense+7",
  },

  // ---- 素材(plan/equipment-forging.md) ----
  {
    id: "hokoraDust",
    name: "ほこら粉",
    category: "material",
    model: "herb",
    minFloor: 1,
    weight: 8,
    description: "ゲンドの工房で、武器・盾の強化や印刻みに使う。",
  },
  {
    id: "markStonePurun",
    name: "ぷるんの刻印石",
    category: "material",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "ゲンドの工房で盾に刻める。被弾ダメージを確率5割で1割軽減する。",
  },
  {
    id: "markStoneGajiri",
    name: "ガジリねずみの刻印石",
    category: "material",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。そのランの最初の1手を必ず会心にする。",
  },
  {
    id: "markStoneTsubute",
    name: "ツブテガエルの刻印石",
    category: "material",
    model: "herb",
    minFloor: 4,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。タルを投げたときのダメージ+2。",
  },
  {
    id: "markStoneMadoromi",
    name: "マドロミダケの刻印石",
    category: "material",
    model: "herb",
    minFloor: 5,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。攻撃時、眠り付与の確率+10%。",
  },
  {
    id: "markStoneHonegarami",
    name: "ホネガラミの刻印石",
    category: "material",
    model: "herb",
    minFloor: 7,
    weight: 2,
    description: "ゲンドの工房で盾に刻める。HPが1残っていれば、致死ダメージを1回だけ耐える。",
  },
];

const BY_ID = new Map(ITEMS.map((i) => [i.id, i]));

export function itemDef(id: string): ItemDef {
  const def = BY_ID.get(id);
  if (!def) throw new Error(`未知のアイテム: ${id}`);
  return def;
}

export function itemsForDepth(depth: number): ItemDef[] {
  return ITEMS.filter((i) => depth >= i.minFloor);
}
