import type { ItemDef } from "../core/types";

/**
 * アイテム図鑑。名前はすべてオリジナル(一般的なファンタジー語彙)。
 * model は public/models/<model>.glb に対応し、同じカテゴリは同じモデルを色違いで使う。
 */
export const ITEMS: readonly ItemDef[] = [
  // ---- 草 ----
  {
    id: "healLeaf",
    name: "いやしの葉",
    category: "herb",
    model: "herb",
    effect: "heal",
    power: 25,
    minFloor: 1,
    weight: 12,
    description: "HPを25回復する。",
  },
  {
    id: "greatLeaf",
    name: "大いやしの葉",
    category: "herb",
    model: "herb",
    effect: "heal",
    power: 60,
    minFloor: 4,
    weight: 5,
    description: "HPを60回復する。",
  },
  {
    id: "powerLeaf",
    name: "ちからの葉",
    category: "herb",
    model: "herb",
    effect: "power",
    power: 1,
    minFloor: 3,
    weight: 3,
    description: "attackが永続的に1上がる。",
  },
  {
    id: "wakeGrass",
    name: "めざめ草",
    category: "herb",
    model: "herb",
    effect: "cureSleepConfuse",
    minFloor: 2,
    weight: 5,
    description: "眠り・混乱を即座に治す。",
  },
  {
    id: "antidoteBerry",
    name: "毒消しの実",
    category: "herb",
    model: "herb",
    effect: "curePoison",
    minFloor: 2,
    weight: 5,
    description: "毒を即座に治す。",
  },
  {
    id: "toughLeaf",
    name: "がんじょうの葉",
    category: "herb",
    model: "herb",
    effect: "defenseUp",
    power: 1,
    minFloor: 3,
    weight: 3,
    description: "defenseが永続的に1上がる。",
  },
  {
    id: "waypointLeaf",
    name: "みちしるべの葉",
    category: "herb",
    model: "herb",
    effect: "senseStairs",
    minFloor: 1,
    weight: 6,
    description: "階段の位置と、そこまでの大まかな道筋だけが分かる。",
  },

  // ---- 巻物 ----
  {
    id: "sleepScroll",
    name: "ねむりの巻物",
    category: "scroll",
    model: "scroll",
    effect: "sleepRoom",
    power: 8,
    minFloor: 2,
    weight: 6,
    description: "同じ部屋のモンスターを眠らせる。",
  },
  {
    id: "mapScroll",
    name: "地図の巻物",
    category: "scroll",
    model: "scroll",
    effect: "revealMap",
    minFloor: 1,
    weight: 7,
    description: "このフロアの地形がすべて分かる。",
  },
  {
    id: "confuseScroll",
    name: "混乱の巻物",
    category: "scroll",
    model: "scroll",
    effect: "confuseRoom",
    power: 8,
    minFloor: 3,
    weight: 5,
    description: "同じ部屋のモンスターを混乱させる。",
  },
  {
    id: "invisibilityScroll",
    name: "とうめいの巻物",
    category: "scroll",
    model: "scroll",
    effect: "invisibility",
    power: 5,
    minFloor: 4,
    weight: 4,
    description: "数ターンの間、モンスターに新たに発見されなくなる。",
  },
  {
    id: "fearScroll",
    name: "おびえの巻物",
    category: "scroll",
    model: "scroll",
    effect: "fearRoom",
    power: 6,
    minFloor: 2,
    weight: 5,
    description: "同じ部屋のモンスターをおびえさせ、逃走させる。",
  },

  // ---- 杖 ----
  {
    id: "swapStaff",
    name: "場所替えの杖",
    category: "staff",
    model: "staff",
    effect: "swap",
    charges: 4,
    minFloor: 2,
    weight: 5,
    description: "向いている方向のモンスターと位置を入れ替える。",
  },
  {
    id: "sleepStaff",
    name: "ねむりの杖",
    category: "staff",
    model: "staff",
    effect: "sleepTarget",
    power: 6,
    charges: 4,
    minFloor: 3,
    weight: 5,
    description: "向いている方向のモンスターを眠らせる。",
  },
  {
    id: "pullStaff",
    name: "引き寄せの杖",
    category: "staff",
    model: "staff",
    effect: "pull",
    charges: 4,
    minFloor: 3,
    weight: 4,
    description: "向いている方向のモンスターを1マス引き寄せる。",
  },
  {
    id: "sealStaff",
    name: "かなしばりの杖",
    category: "staff",
    model: "staff",
    effect: "sealTarget",
    power: 6,
    charges: 4,
    minFloor: 4,
    weight: 4,
    description: "向いている方向のモンスターを封じる(特技が使えなくなる)。",
  },

  // ---- 食料 ----
  {
    id: "hardBread",
    name: "かたパン",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 45,
    minFloor: 1,
    weight: 10,
    description: "満腹度を45回復する。",
  },
  {
    id: "bigBread",
    name: "大きなパン",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 100,
    minFloor: 3,
    weight: 4,
    description: "満腹度を100回復する。",
  },
  {
    id: "mountainBounty",
    name: "山の幸",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 150,
    minFloor: 6,
    weight: 3,
    description: "満腹度を150回復する。",
  },
  {
    id: "driedBerries",
    name: "ほしぼし",
    category: "food",
    model: "bread",
    effect: "eat",
    power: 15,
    minFloor: 1,
    weight: 10,
    description: "満腹度を15回復する。軽くて持ち歩きやすい。",
  },

  // ---- 武器 ----
  // 系統ごとに attackPattern が異なる。plan/protagonist-weapons.md 参照。
  // 各系統は入手階層違いの基本形・上位形の2段構成(既存のなた/鉄のなたと揃える)。
  {
    id: "hatchet",
    name: "なた",
    category: "weapon",
    model: "hatchet",
    bonus: 4,
    minFloor: 1,
    weight: 5,
    description: "attack+4。隣接1マスを攻撃する、もっとも素直な性能。",
  },
  {
    id: "ironHatchet",
    name: "鉄のなた",
    category: "weapon",
    model: "hatchet",
    bonus: 9,
    minFloor: 5,
    weight: 3,
    description: "attack+9。隣接1マスを攻撃する、もっとも素直な性能。",
  },
  {
    id: "spearedge",
    name: "穂突き",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "line2",
    minFloor: 2,
    weight: 4,
    description: "attack+3。正面2マス先まで直線に届く(間の敵も巻き込む)。",
  },
  {
    id: "greatSpearedge",
    name: "長穂突き",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "line2",
    minFloor: 6,
    weight: 3,
    description: "attack+7。正面2マス先まで直線に届く(間の敵も巻き込む)。",
  },
  {
    id: "broadaxe",
    name: "大鉈",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "arc3",
    minFloor: 3,
    weight: 4,
    description: "attack+3。向いている方向を中心に正面と斜め前2方向、計3マスを攻撃する。",
  },
  {
    id: "greatBroadaxe",
    name: "大鉈・重",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "arc3",
    minFloor: 7,
    weight: 3,
    description: "attack+7。向いている方向を中心に正面と斜め前2方向、計3マスを攻撃する。",
  },
  {
    id: "barrelHook",
    name: "双樽鉤",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "quickSingle",
    minFloor: 4,
    weight: 4,
    description: "attack+3。会心率+15%、そのラン最初の1手は必ず会心の一撃になる。",
  },
  {
    id: "greatBarrelHook",
    name: "双樽鉤・双牙",
    category: "weapon",
    model: "hatchet",
    bonus: 7,
    attackPattern: "quickSingle",
    minFloor: 8,
    weight: 3,
    description: "attack+7。会心率+15%、そのラン最初の1手は必ず会心の一撃になる。",
  },
  {
    id: "lordsMaul",
    name: "主の大槌",
    category: "weapon",
    model: "hatchet",
    bonus: 6,
    attackPattern: "heavySingle",
    minFloor: 5,
    weight: 3,
    description: "attack+6。振るった反動で、次の1手ぶん行動が遅れる。",
  },
  {
    id: "greatLordsMaul",
    name: "主の大槌・銘",
    category: "weapon",
    model: "hatchet",
    bonus: 12,
    attackPattern: "heavySingle",
    minFloor: 9,
    weight: 2,
    description: "attack+12。振るった反動で、次の1手ぶん行動が遅れる。",
  },

  // ---- NPCサイドストーリー(plan/side-stories-part1.md)の専用武器 ----
  // ダンジョンでは拾えない(minFloor: Infinity・weight: 0)。性能は元の系統と同格で、
  // 譲り受けるNPC・逸話が違うだけの専用個体
  {
    id: "mogurababaKeepsakeHatchet",
    name: "モグラ婆の形見のなた",
    category: "weapon",
    model: "hatchet",
    bonus: 4,
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "attack+4。隣接1マスを攻撃する。モグラ婆が若い頃に使っていたという、なたの形見。",
  },
  {
    id: "gendoPhantomBillhook",
    name: "まぼろしの大鉈",
    category: "weapon",
    model: "hatchet",
    bonus: 3,
    attackPattern: "arc3",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "attack+3。向いている方向を中心に正面と斜め前2方向、計3マスを攻撃する。ゲンドが語っていた会心の一振りを再現したもの。",
  },

  // ---- 盾 ----
  {
    id: "woodShield",
    name: "木の盾",
    category: "shield",
    model: "shield",
    bonus: 3,
    minFloor: 1,
    weight: 5,
    description: "defense+3",
  },
  {
    id: "ironShield",
    name: "鉄の盾",
    category: "shield",
    model: "shield",
    bonus: 7,
    minFloor: 5,
    weight: 3,
    description: "defense+7",
  },

  // ---- 素材(plan/equipment-forging.md) ----
  {
    id: "hokoraDust",
    name: "ほこら粉",
    category: "material",
    model: "herb",
    minFloor: 1,
    weight: 8,
    description: "ゲンドの工房で、武器・盾の強化や印刻みに使う。",
  },
  {
    id: "markStonePurun",
    name: "ぷるんの刻印石",
    category: "material",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "ゲンドの工房で盾に刻める。被弾ダメージを確率5割で1割軽減する。",
  },
  {
    id: "markStoneGajiri",
    name: "ガジリねずみの刻印石",
    category: "material",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。そのランの最初の1手を必ず会心にする。",
  },
  {
    id: "markStoneTsubute",
    name: "ツブテガエルの刻印石",
    category: "material",
    model: "herb",
    minFloor: 4,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。タルを投げたときのダメージ+2。",
  },
  {
    id: "markStoneMadoromi",
    name: "マドロミダケの刻印石",
    category: "material",
    model: "herb",
    minFloor: 5,
    weight: 2,
    description: "ゲンドの工房で武器に刻める。攻撃時、眠り付与の確率+10%。",
  },
  {
    id: "markStoneHonegarami",
    name: "ホネガラミの刻印石",
    category: "material",
    model: "herb",
    minFloor: 7,
    weight: 2,
    description: "ゲンドの工房で盾に刻める。HPが1残っていれば、致死ダメージを1回だけ耐える。",
  },
  {
    // 2つ目の刻印を可能にする条件(plan/dual-mark-equipment.md)。ゲンドの
    // 工房で刻印石2つ+ほこら粉から合成する専用素材。ダンジョンでの直接
    // ドロップにはしない(minFloor: Infinity・weight: 0で除外)
    id: "overlayMarkStone",
    name: "重ね刻みの砥石",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "ゲンドの工房で、+9の装備に2つ目の印を刻めるようにする。",
  },
  {
    // 地方ボス(plan/region-bosses.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "oonebosukeDust",
    name: "おおねぼすけの眠り粉",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "うたたねの参道の主を倒した証。ゲンドの工房でも珍しがられる、上質な粉。",
  },
  {
    // 地方ボス(plan/region-boss-nushigaeru.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "nushigaeruUroko",
    name: "ヌシガエルのうろこ",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "忘れ潮の湿地の主を倒した証。水を弾く、分厚くしなやかなうろこ。",
  },
  {
    // 地方ボス(plan/region-boss-oomadoromi.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "oomadoromiHoushi",
    name: "オオマドロミの胞子玉",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "まどろみの茸林の主を倒した証。触れるとかすかに眠気を誘う、丸い胞子の塊。",
  },
  {
    // 地方ボス(plan/region-boss-honezuka.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "honezukaKotsuban",
    name: "ホネヅカの骨盤",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "骨積みの回廊の主を倒した証。無数の骨の重みを支え続けた、頑丈な骨盤。",
  },
  {
    // 地方ボス(plan/region-boss-fuchinonushi.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "fuchiNoNushiNoUroko",
    name: "淵の主のうろこ",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "なみだの滝つぼの主を倒した証。冷たく重い、水底の記憶を宿すうろこ。",
  },
  {
    // 地方ボス(plan/region-boss-kodamanonushi.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "kodamaNoKakera",
    name: "こだまのかけら",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "こだまの尾根の主を倒した証。耳を近づけると、かすかに声の反響が聞こえる。",
  },
  {
    // 地方ボス(plan/region-boss-misemonononushi.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "misemonoNoOmen",
    name: "見世物の面",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "わすれられた祭りの跡の主を倒した証。ひび割れた、呼び込みの面。",
  },
  {
    // 地方ボス(plan/region-boss-horikuinonushi.md)を撃破した確定ドロップ専用。
    // ランダムな床落ちには出さない(minFloor: Infinity・weight: 0で除外)
    id: "horikuiNoKuiSaki",
    name: "掘り杭の杭先",
    category: "material",
    model: "herb",
    minFloor: Number.POSITIVE_INFINITY,
    weight: 0,
    description: "めざめの前庭の主を倒した証。ヨリシロの夢と混ざり合った、杭の先端。",
  },

  // ---- 頭防具(plan/protagonist-equipment.md) ----
  {
    id: "barrelGuardHat",
    name: "樽守りの笠",
    category: "head",
    model: "shield",
    minFloor: 1,
    weight: 3,
    description: "状態異常(眠り)にかかりにくくなる。",
  },
  {
    id: "lookoutHeadband",
    name: "見晴らしのはちまき",
    category: "head",
    model: "shield",
    minFloor: 3,
    weight: 3,
    description: "視界がわずかに広がる。",
  },
  {
    id: "ironHelm",
    name: "鉄兜",
    category: "head",
    model: "shield",
    bonus: 2,
    minFloor: 6,
    weight: 2,
    description: "defense+2。ただし状態異常への耐性は無い。",
  },
  {
    id: "farsightRing",
    name: "千里眼の輪",
    category: "head",
    model: "shield",
    minFloor: 10,
    weight: 2,
    description: "モンスターハウスの気配を、より手前で察知できる。",
  },

  // ---- 装身具(plan/protagonist-equipment.md) ----
  {
    id: "fulfillingStone",
    name: "満たされ石",
    category: "charm",
    model: "herb",
    minFloor: 1,
    weight: 3,
    description: "満腹度の減りがゆるやかになる。",
  },
  {
    id: "barrelKinshipBracelet",
    name: "樽なじみの腕輪",
    category: "charm",
    model: "herb",
    minFloor: 2,
    weight: 3,
    description: "からのタルでモンスターを吸い込める確率が上がる。",
  },
  {
    id: "guardianBell",
    name: "身がわりの鈴",
    category: "charm",
    model: "herb",
    minFloor: 4,
    weight: 2,
    description: "HPが1残っていれば、致死ダメージを1回だけ耐える(1ダイブ1回)。",
  },
  {
    id: "dustLureSachet",
    name: "ほこら粉寄せの匂い袋",
    category: "charm",
    model: "herb",
    minFloor: 3,
    weight: 2,
    description: "ほこら粉が見つかりやすくなる。",
  },

  // ---- 道具(plan/protagonist-equipment.md) ----
  {
    id: "ashfireDust",
    name: "送り火の粉",
    category: "tool",
    model: "herb",
    minFloor: 1,
    weight: 2,
    description: "その場でダイブを打ち切り、持ち物・仲間を持ったまま麓へ戻る。",
  },
  {
    id: "barrelAppraisal",
    name: "樽の目利き",
    category: "tool",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "視界内のモンスター入りのタルの中身を見分ける。",
  },
  {
    id: "homesickRope",
    name: "望郷の綱",
    category: "tool",
    model: "herb",
    minFloor: 2,
    weight: 2,
    description: "はぐれた仲間を、その場に強制的に呼び寄せる。",
  },
  {
    id: "torch",
    name: "松明",
    category: "tool",
    model: "herb",
    // 第四地方(19階)以降でくらやみの階が出やすくなる(plan/region-darkness.md)のに
    // 合わせ、その手前から持てるようにする。通常の階でも使える
    minFloor: 15,
    weight: 3,
    description: "しばらくのあいだ、視界がぐっと広がる。くらやみの階でとくに頼りになる。",
  },
];

const BY_ID = new Map(ITEMS.map((i) => [i.id, i]));

export function itemDef(id: string): ItemDef {
  const def = BY_ID.get(id);
  if (!def) throw new Error(`未知のアイテム: ${id}`);
  return def;
}

export function itemsForDepth(depth: number): ItemDef[] {
  return ITEMS.filter((i) => depth >= i.minFloor);
}
